// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: hello/hellopb/hellopb.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelloServiceClient is the client API for HelloService server.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloServiceClient interface {
	// unary
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	//server streaming
	// server return a greeting in different languages
	HelloManyLanguages(ctx context.Context, in *HelloManyLanguagesRequest, opts ...grpc.CallOption) (HelloService_HelloManyLanguagesClient, error)
	// server client streaming
	// send many hellos and response with goodbye for all people
	HelloGoodBye(ctx context.Context, opts ...grpc.CallOption) (HelloService_HelloGoodByeClient, error)
	// server bidirectional streaming
	GoodBye(ctx context.Context, opts ...grpc.CallOption) (HelloService_GoodByeClient, error)
}

type helloServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloServiceClient(cc grpc.ClientConnInterface) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/hello.HelloService/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) HelloManyLanguages(ctx context.Context, in *HelloManyLanguagesRequest, opts ...grpc.CallOption) (HelloService_HelloManyLanguagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &HelloService_ServiceDesc.Streams[0], "/hello.HelloService/HelloManyLanguages", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServiceHelloManyLanguagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HelloService_HelloManyLanguagesClient interface {
	Recv() (*HelloManyLanguagesResponse, error)
	grpc.ClientStream
}

type helloServiceHelloManyLanguagesClient struct {
	grpc.ClientStream
}

func (x *helloServiceHelloManyLanguagesClient) Recv() (*HelloManyLanguagesResponse, error) {
	m := new(HelloManyLanguagesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloServiceClient) HelloGoodBye(ctx context.Context, opts ...grpc.CallOption) (HelloService_HelloGoodByeClient, error) {
	stream, err := c.cc.NewStream(ctx, &HelloService_ServiceDesc.Streams[1], "/hello.HelloService/HelloGoodBye", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServiceHelloGoodByeClient{stream}
	return x, nil
}

type HelloService_HelloGoodByeClient interface {
	Send(*HelloGodByeRequest) error
	CloseAndRecv() (*HelloGodByeResponse, error)
	grpc.ClientStream
}

type helloServiceHelloGoodByeClient struct {
	grpc.ClientStream
}

func (x *helloServiceHelloGoodByeClient) Send(m *HelloGodByeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloServiceHelloGoodByeClient) CloseAndRecv() (*HelloGodByeResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloGodByeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloServiceClient) GoodBye(ctx context.Context, opts ...grpc.CallOption) (HelloService_GoodByeClient, error) {
	stream, err := c.cc.NewStream(ctx, &HelloService_ServiceDesc.Streams[2], "/hello.HelloService/GoodBye", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServiceGoodByeClient{stream}
	return x, nil
}

type HelloService_GoodByeClient interface {
	Send(*HelloGodByeRequest) error
	Recv() (*HelloGodByeResponse, error)
	grpc.ClientStream
}

type helloServiceGoodByeClient struct {
	grpc.ClientStream
}

func (x *helloServiceGoodByeClient) Send(m *HelloGodByeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloServiceGoodByeClient) Recv() (*HelloGodByeResponse, error) {
	m := new(HelloGodByeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HelloServiceServer is the server API for HelloService server.
// All implementations must embed UnimplementedHelloServiceServer
// for forward compatibility
type HelloServiceServer interface {
	// unary
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	//server streaming
	// server return a greeting in different languages
	HelloManyLanguages(*HelloManyLanguagesRequest, HelloService_HelloManyLanguagesServer) error
	// server client streaming
	// send many hellos and response with goodbye for all people
	HelloGoodBye(HelloService_HelloGoodByeServer) error
	// server bidirectional streaming
	GoodBye(HelloService_GoodByeServer) error
	mustEmbedUnimplementedHelloServiceServer()
}

// UnimplementedHelloServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHelloServiceServer struct {
}

func (UnimplementedHelloServiceServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedHelloServiceServer) HelloManyLanguages(*HelloManyLanguagesRequest, HelloService_HelloManyLanguagesServer) error {
	return status.Errorf(codes.Unimplemented, "method HelloManyLanguages not implemented")
}
func (UnimplementedHelloServiceServer) HelloGoodBye(HelloService_HelloGoodByeServer) error {
	return status.Errorf(codes.Unimplemented, "method HelloGoodBye not implemented")
}
func (UnimplementedHelloServiceServer) GoodBye(HelloService_GoodByeServer) error {
	return status.Errorf(codes.Unimplemented, "method GoodBye not implemented")
}
func (UnimplementedHelloServiceServer) mustEmbedUnimplementedHelloServiceServer() {}

// UnsafeHelloServiceServer may be embedded to opt out of forward compatibility for this server.
// Use of this interface is not recommended, as added methods to HelloServiceServer will
// result in compilation errors.
type UnsafeHelloServiceServer interface {
	mustEmbedUnimplementedHelloServiceServer()
}

func RegisterHelloServiceServer(s grpc.ServiceRegistrar, srv HelloServiceServer) {
	s.RegisterService(&HelloService_ServiceDesc, srv)
}

func _HelloService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.HelloService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_HelloManyLanguages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloManyLanguagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HelloServiceServer).HelloManyLanguages(m, &helloServiceHelloManyLanguagesServer{stream})
}

type HelloService_HelloManyLanguagesServer interface {
	Send(*HelloManyLanguagesResponse) error
	grpc.ServerStream
}

type helloServiceHelloManyLanguagesServer struct {
	grpc.ServerStream
}

func (x *helloServiceHelloManyLanguagesServer) Send(m *HelloManyLanguagesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _HelloService_HelloGoodBye_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServiceServer).HelloGoodBye(&helloServiceHelloGoodByeServer{stream})
}

type HelloService_HelloGoodByeServer interface {
	SendAndClose(*HelloGodByeResponse) error
	Recv() (*HelloGodByeRequest, error)
	grpc.ServerStream
}

type helloServiceHelloGoodByeServer struct {
	grpc.ServerStream
}

func (x *helloServiceHelloGoodByeServer) SendAndClose(m *HelloGodByeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloServiceHelloGoodByeServer) Recv() (*HelloGodByeRequest, error) {
	m := new(HelloGodByeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HelloService_GoodBye_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServiceServer).GoodBye(&helloServiceGoodByeServer{stream})
}

type HelloService_GoodByeServer interface {
	Send(*HelloGodByeResponse) error
	Recv() (*HelloGodByeRequest, error)
	grpc.ServerStream
}

type helloServiceGoodByeServer struct {
	grpc.ServerStream
}

func (x *helloServiceGoodByeServer) Send(m *HelloGodByeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloServiceGoodByeServer) Recv() (*HelloGodByeRequest, error) {
	m := new(HelloGodByeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HelloService_ServiceDesc is the grpc.ServiceDesc for HelloService server.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _HelloService_Hello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HelloManyLanguages",
			Handler:       _HelloService_HelloManyLanguages_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "HelloGoodBye",
			Handler:       _HelloService_HelloGoodBye_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GoodBye",
			Handler:       _HelloService_GoodBye_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hello/hellopb/hellopb.proto",
}
